[versions]
jackson = "2.19.1"
junit5 = "5.13.2"
mockito = "5.18.0"
slf4j = "2.0.17"
jetty = "12.0.22"
hazelcast = "5.5.0"
tika = "3.2.0"
micrometer = "1.15.2"
prometheus = "1.3.8"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit5" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junitjupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }

equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version = "4.0.3" }

assertj-core = { module = "org.assertj:assertj-core", version = "3.27.3" }

tinybundles = { module = "org.ops4j.pax.tinybundles:tinybundles", version = "4.0.1" }

mockjavamail = { module = "org.jvnet.mock-javamail:mock-javamail", version = "2.2" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
slf4j-jultoslf4j = { module = "org.slf4j:jul-to-slf4j", version.ref = "slf4j" }
slf4j-jcloverslf4j= { module = "org.slf4j:jcl-over-slf4j", version.ref = "slf4j" }
slf4j-log4joverslf4j = { module = "org.slf4j:log4j-over-slf4j", version.ref = "slf4j" }
jboss-logging = { module = "org.jboss.logging:jboss-logging", version = "3.6.1.Final" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.18" }

jakarta-activation = { module = "com.sun.activation:jakarta.activation", version = "2.0.1" }
jakarta-mail = { module = "com.sun.mail:jakarta.mail", version = "2.0.1" }
jakarta-annotation = { module = "jakarta.annotation:jakarta.annotation-api", version = "2.1.1" }
jakarta-validation = { module = "jakarta.validation:jakarta.validation-api", version = "3.0.2" }
jakarta-jaxrs = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version = "3.1.0" }

jakarta-servlet = "jakarta.servlet:jakarta.servlet-api:6.1.0"
jakarta-websocket-clientapi = "jakarta.websocket:jakarta.websocket-client-api:2.1.0"

osgi-service-component = { module = "org.osgi:org.osgi.service.component", version = "1.5.1" }
osgi-service-componentannotations = { module = "org.osgi:org.osgi.service.component.annotations", version = "1.5.1" }
osgi-service-cm = { module = "org.osgi:org.osgi.service.cm", version = "1.6.1" }
osgi-util-promise = { module = "org.osgi:org.osgi.util.promise", version = "1.3.0" }
osgi-util-function = { module = "org.osgi:org.osgi.util.function", version = "1.2.0" }
osgi-core = { module = "org.osgi:osgi.core", version = "8.0.0" }

felix-metatype = { module = "org.apache.felix:org.apache.felix.metatype", version = "1.2.4" }
felix-eventadmin = { module = "org.apache.felix:org.apache.felix.eventadmin", version = "1.6.4" }
felix-configadmin = { module = "org.apache.felix:org.apache.felix.configadmin", version = "1.9.26" }
felix-scr = { module = "org.apache.felix:org.apache.felix.scr", version = "2.2.12" }
felix-framework = { module = "org.apache.felix:org.apache.felix.framework", version = "7.0.5" }
felix-utils = { module = "org.apache.felix:org.apache.felix.utils", version = "1.11.8" }
felix-log = { module = "org.apache.felix:org.apache.felix.log", version = "1.3.0" }

bcprov-jdk18on = { module = "org.bouncycastle:bcprov-jdk18on", version = "1.81" }

elasticsearch = { module = "org.elasticsearch:elasticsearch", version = "2.4.6" }

jna = { module = "net.java.dev.jna:jna", version = "4.1.0" }

findbugs-jsr305 = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }

guava-guava = { module = "com.google.guava:guava", version = "33.4.8-jre" }
guava-failureaccess = { module = "com.google.guava:failureaccess", version = "1.0.3" }

jsoup = { module = "org.jsoup:jsoup", version = "1.21.1" }

owaspsanitizer = { module = "com.googlecode.owasp-java-html-sanitizer:owasp-java-html-sanitizer", version = "20240325.1" }

bytebuddy = { module = "net.bytebuddy:byte-buddy", version = "1.17.6" }

cronutils = { module = "com.cronutils:cron-utils", version = "9.2.1" }

jhlabs-filters = { module = "com.jhlabs:filters", version = "2.0.235-1" }

attoparser = { module = "org.attoparser:attoparser", version = "1.3" }

nashorn = { module = "org.openjdk.nashorn:nashorn-core", version = "15.6" }
graalvm-polyglot = { module = "org.graalvm.polyglot:polyglot", version = "23.1.7" }
graalvm-js = { module = "org.graalvm.polyglot:js", version = "23.1.7" }
graalvm-jsse = { module = "org.graalvm.js:js-scriptengine", version = "23.1.7" }

commons-lang3 = { module = "org.apache.commons:commons-lang3", version = "3.17.0" }
commons-io = { module = "commons-io:commons-io", version = "2.19.0" }
commons-compress = { module = "org.apache.commons:commons-compress", version = "1.27.1" }

jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-jakarta-base = { module = "com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-base", version.ref = "jackson" }
jackson-jakarta-jsonprovider = { module = "com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-json-provider", version.ref = "jackson" }
jackson-dataformat-smile = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-smile", version.ref = "jackson" }
jackson-dataformat-cbor = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-cbor", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }

tika-core = { module = "org.apache.tika:tika-core", version.ref = "tika" }
tika-bundlestandard = { module = "org.apache.tika:tika-bundle-standard", version.ref = "tika" }
tika-parser-apple = { module = "org.apache.tika:tika-parser-apple-module", version.ref = "tika" }
tika-parser-audiovideo = { module = "org.apache.tika:tika-parser-audiovideo-module", version.ref = "tika" }
tika-parser-cad = { module = "org.apache.tika:tika-parser-cad-module", version.ref = "tika" }
tika-parser-code = { module = "org.apache.tika:tika-parser-code-module", version.ref = "tika" }
tika-parser-crypto = { module = "org.apache.tika:tika-parser-crypto-module", version.ref = "tika" }
tika-parser-digestcommons = { module = "org.apache.tika:tika-parser-digest-commons", version.ref = "tika" }
tika-parser-font = { module = "org.apache.tika:tika-parser-font-module", version.ref = "tika" }
tika-parser-html = { module = "org.apache.tika:tika-parser-html-module", version.ref = "tika" }
tika-parser-image = { module = "org.apache.tika:tika-parser-image-module", version.ref = "tika" }
tika-parser-mail = { module = "org.apache.tika:tika-parser-mail-module", version.ref = "tika" }
tika-parser-mailcommons = { module = "org.apache.tika:tika-parser-mail-commons", version.ref = "tika" }
tika-parser-microsoft = { module = "org.apache.tika:tika-parser-microsoft-module", version.ref = "tika" }
tika-parser-miscoffice = { module = "org.apache.tika:tika-parser-miscoffice-module", version.ref = "tika" }
tika-parser-news = { module = "org.apache.tika:tika-parser-news-module", version.ref = "tika" }
tika-parser-ocr = { module = "org.apache.tika:tika-parser-ocr-module", version.ref = "tika" }
tika-parser-pdf = { module = "org.apache.tika:tika-parser-pdf-module", version.ref = "tika" }
tika-parser-pkg = { module = "org.apache.tika:tika-parser-pkg-module", version.ref = "tika" }
tika-parser-text = { module = "org.apache.tika:tika-parser-text-module", version.ref = "tika" }
tika-parser-webarchive = { module = "org.apache.tika:tika-parser-webarchive-module", version.ref = "tika" }
tika-parser-xml = { module = "org.apache.tika:tika-parser-xml-module", version.ref = "tika" }
tika-parser-xmpcommons = { module = "org.apache.tika:tika-parser-xmp-commons", version.ref = "tika" }
tika-parser-zipcommons = { module = "org.apache.tika:tika-parser-zip-commons", version.ref = "tika" }

hazelcast-hazelcast = { module = "com.hazelcast:hazelcast", version.ref = "hazelcast" }

jparsec = { module = "org.jparsec:jparsec", version = "3.1" }

resteasy = { module = "org.jboss.resteasy:resteasy-core", version = "6.2.12.Final" }

jetty-server = { module = "org.eclipse.jetty:jetty-server", version.ref = "jetty" }
jetty-servlet = { module = "org.eclipse.jetty.ee10:jetty-ee10-servlet", version.ref = "jetty" }
jetty-servlets = { module = "org.eclipse.jetty.ee10:jetty-ee10-servlets", version.ref = "jetty" }
jetty-jmx = { module = "org.eclipse.jetty:jetty-jmx", version.ref = "jetty" }
jetty-websocket-server = { module = "org.eclipse.jetty.ee10.websocket:jetty-ee10-websocket-jakarta-server", version.ref = "jetty" }
jetty-hazelcast = { module = "org.eclipse.jetty:jetty-hazelcast", version.ref = "jetty" }

micrometer-commons = { module = "io.micrometer:micrometer-commons", version.ref = "micrometer" }
micrometer-core = { module = "io.micrometer:micrometer-core", version.ref = "micrometer" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer" }
micrometer-jetty12 = { module = "io.micrometer:micrometer-jetty12", version.ref = "micrometer" }

prometheus-metrics-config = { module = "io.prometheus:prometheus-metrics-config", version.ref = "prometheus" }
prometheus-metrics-core = { module = "io.prometheus:prometheus-metrics-core", version.ref = "prometheus" }
prometheus-metrics-exposition-formats = { module = "io.prometheus:prometheus-metrics-exposition-formats", version.ref = "prometheus" }
prometheus-metrics-exposition-textformats = { module = "io.prometheus:prometheus-metrics-exposition-textformats", version.ref = "prometheus" }
prometheus-metrics-model = { module = "io.prometheus:prometheus-metrics-model", version.ref = "prometheus" }
prometheus-metrics-tracer-common = { module = "io.prometheus:prometheus-metrics-tracer-common", version.ref = "prometheus" }

[plugins]
